### ISSUE TITLE
Is it possible to export Org mode documents to PDF?

### ISSUE THREAD

**Issue by avatar-lavventura** [wallyqs/org-ruby#100]
I was wondering Is it possible to export Org mode documents to PDF? Could it be implemented as a feature?

**Comment by maxnikulin** [comment]
Org mode as Emacs major mode uses LaTeX as intermediate format to export to PDF, see [LaTeX Export](https://orgmode.org/manual/LaTeX-Export.html) in the Org manual.

In the scope of org-ruby, you may render a document to HTML and print it to PDF
```
chromium --headless --disable-gpu --print-to-pdf=output_file_name.pdf file:///path/to/your/html
```

https://github.com/jgm/pandoc/ uses PdfLaTeX as well (`-t pdf`).

**Comment by avatar-lavventura** [comment]
@maxnikulin Thank you
