### ISSUE TITLE
Normalize the name being used for syntax highlighting

### ISSUE THREAD

**Issue by wallyqs** [wallyqs/org-ruby#14]
Take a look at those defined in linguist and the oned being used in emacs.

**Comment by waldyrious** [comment]
@wallyqs how does this issue (and https://github.com/github/markup/issues/310) relate to the normalizing done [here](https://github.com/wallyqs/org-ruby/blob/dd04a1d35f9aa9f3ff6289ac24bde5cf2af56a74/lib/org-ruby/html_output_buffer.rb#L363)? Is it no longer needed?

**Comment by wallyqs** [comment]
@waldyrious it was used so that in case there is a mismatch between the emacs mode and the expected language name used in the code block
