### ISSUE TITLE
Change "_word_" to generic span "underline" rather than in-line text-decoration.

### ISSUE THREAD

**Issue by mashdot** [wallyqs/org-ruby#29]
I just spotted that when I use:

`_word_`

It is parsed to:

`<span style="text-decoration:underline;">word</span>`

I am wanting to use underline as a means to highlight text in a document. Unfortunately [`<mark>` is not supported in org-mode](http://lists.gnu.org/archive/html/emacs-orgmode/2014-08/msg00106.html), and so I would like to request the following output:

`<span class="underline">word</span>`

This would allow us to define and manage `underline` in CSS directly, which I feel is more useful then in-line styling.

Thoughts?

Note: Originally posted to: https://github.com/eggcaker/jekyll-org/issues/7 and https://github.com/bdewey/org-ruby/issues/64

**Comment by mashdot** [comment]
Also may be worth creating something new like:

`!word!`

Parsed to:

`<mark>word</mark>`

**Comment by wallyqs** [comment]
In org-ruby you may be able to workaround by overriding the markup: https://github.com/wallyqs/org-ruby#html-emphasis

**Comment by mashdot** [comment]
Thanks, will have a look at jigging `jekyll-org` to use `{ markup_file: "html.tags.yml" }`.

**Comment by gnusosa** [comment]
@mashdot Sorry I'm late on this reply, but it works perfectly for me. Just modify line 37 in `convert.rb` of `jekyll-org` to this:

````ruby
org_text = Orgmode::Parser.new(content,  { markup_file: "/home/user/html.tags.yml" })
````

You have to add the full path for `html.tags.yml` in order to work outside your working jekyll directory.

**Comment by mashdot** [comment]
Thanks! Been busy so didn't look much more into this.
