### ISSUE TITLE
Characters in HTML blocks are converted to character references

### ISSUE THREAD

**Issue by scalisi** [wallyqs/org-ruby#30]
Hi @wallyqs,

My Org files include YAML front matter inside `#+begin_html` and `#+end_html`. When I convert these Org files to HTML using `org-export-dispatch`, the YAML front matter is exported raw as expected. But when I convert these Org files to HTML using org-ruby, the triple hyphens `---` are converted to `&#8212;` character references. Is this a bug?

Thanks a lot for all the work you've done on org-ruby!

**Comment by wallyqs** [comment]
There is a `skip_rubypants_pass` option that may be useful to fix this, check it out.

**Comment by scalisi** [comment]
Thanks for your help, @wallyqs!
