### ISSUE TITLE
Continuing numbered lists

### ISSUE THREAD

**Issue by rschuetzler** [wallyqs/org-ruby#38]
Org-mode provides the capability to specify the starting number in a list using a marker of `[@5]` after the number to start the list at 5, for example. This is documented [here](http://orgmode.org/manual/Plain-lists.html) under Ordered list and explained in [this StackOverflow answer](http://stackoverflow.com/a/21475047/1442881).

`Ordered list items start with a numeral followed by either a period or a right parenthesis2, such as ‘1.’ or ‘1)’3. If you want a list to start with a different value (e.g., 20), start the text of the item with [@20]4. Those constructs can be used in any item of the list in order to enforce a particular numbering.`

This currently does not work with `.org` files rendered as markdown on the GitHub site.

**Comment by wallyqs** [comment]
Thanks for the report. Fixed via #40
