### ISSUE TITLE
Bug? Does not export results with :exports both

### ISSUE THREAD

**Issue by ddoherty03** [wallyqs/org-ruby#44]
Writing a README in org for github, I would like to be able to include code snippets that I can just execute in the README and show the results.  I would have thought a header argument of ':exports both' would do the trick, but only the code block shows up on github, not the results.

Is this a bug, or am I doing something wrong here?

**Comment by melioratus** [comment]
@ddoherty03 

I’m having difficulty reproducing the issue. Would you provide a code sample? When I use `:exports both`, I see both the code and the results, e.g. [playing around](https://github.com/melioratus/nosebutter/blob/master/learning-ruby.org#playing-around)

Thanks for your help!
Brian K. ~ @melioratus

**Comment by ddoherty03** [comment]
Hmm.  I can't reproduce it now either.  This issue is quite old, so I will close it and re-raise if I see it again.

Thanks for taking a look.

**Comment by tdehaeze** [comment]
It seems it is related to #62.
