### ISSUE TITLE
Images with hyperlinks that does not end in image formats are not rendered as images although the links still point towards an image

### ISSUE THREAD

**Issue by justinjk007** [wallyqs/org-ruby#49]
For example, the appveyor build badge
```org-mode
[[https://ci.appveyor.com/project/justinjk007/pentagonal-tiling][https://ci.appveyor.com/api/projects/status/ldc8jtft09n5997e?svg=true]] 
```
although it point to an image it won't be rendered as an image but just a common hyperlink.

**Comment by justinjk007** [comment]
@wallyqs i'm sorry .. did this fail to notify you ?

**Comment by akicho8** [comment]
I same problem too.
Because of this problem, I would write it in markdown rather than org-mode.
I am glad if it is corrected.

**Comment by justinjk007** [comment]
@akicho8 do you re-write the entire Readme? Or do you make a small exported portion? I tried exporting with Html but it did now work for me .

**Comment by wallyqs** [comment]
Using html for including the badge would work for now... something like the following syntax in Github:

```
#+html: <a href="https://ci.appveyor.com/project/justinjk007/pentagonal-tiling"> <img src="https://ci.appveyor.com/api/projects/status/ldc8jtft09n5997e?svg=true" alt="Project Badge"> </a>
```

**Comment by akicho8** [comment]
@justinjk007 Because it's for badges, just move a part is fine

@wallyqs I could display it by that method. Thank you

**Comment by wallyqs** [comment]
Fixed via workaround shared above

**Comment by melioratus** [comment]
Here is another potential workaround: Append an anchor with image extention, e.g. `#.svg`, to URL. 

- Original

        [[https://ci.appveyor.com/project/justinjk007/pentagonal-tiling][https://ci.appveyor.com/api/projects/status/ldc8jtft09n5997e?svg=true]]

- Workaround using anchor

        [[https://ci.appveyor.com/project/justinjk007/pentagonal-tiling][https://ci.appveyor.com/api/projects/status/ldc8jtft09n5997e?svg=true#.svg]]

-------

https://gist.github.com/melioratus/831117d190089a20732ec01fa445a834

**Comment by justinjk007** [comment]
@melioratus  oh that is just perfect..
