### ISSUE TITLE
Idea for collaboration

### ISSUE THREAD

**Issue by gitonthescene** [wallyqs/org-ruby#91]
Hello,  I found your project from the [worg tools list](https://orgmode.org/worg/org-tools/index.html).  First, sorry for the semi-spam nature of this issue.  I had a notion for a project that the org community might find useful and I'm looking for feedback.  Feel free to close this issue if it doesn't sound useful to you.

My idea is to start a [list of org-mode snippets](https://github.com/gitonthescene/org-mode-samples) which can serve as a test bed for people developing tools.  The idea is that having a separate collection of repositories makes it easier for others in the community to benefit from the examples developed through communication with users.

Users could use these samples to try to construct minimal examples of issues they're having and/or contribute examples there which others could benefit from.  Exactly how it will take shape is still up in the air.

These samples could also serve as a place to discuss ideas about how to develop the grammar itself.  According to worg, the spec is still in [draft state](https://orgmode.org/worg/dev/org-syntax.html).

There's not much there at the moment.  Mostly because I don't want to commit too early to what seems like it might be useful.  I'll add more examples as I go.

If you like the concept and/or want to contribute and/or just want to offer feedback, I'd very much appreciate it.

Again, sorry for the spam.

**Comment by maker2413** [comment]
I have seen one other person link this repo which has a lot of examples already: https://github.com/novoid/github-orgmode-tests. You could try reaching out to them and seeing if they would be willing to add some of there tests to your org-mode test repo. I think the idea overall is great though and I would like to see it!

**Comment by gitonthescene** [comment]
Thanks for the pointer!  I’ll close this issue now.  If you have any other ideas or suggestions, please feel free to open an issue.

**Comment by maker2413** [comment]
I still think it is a really great idea and if you open source it I would be willing to add to it if I ever get into contributing to this project!

**Comment by gitonthescene** [comment]
Thanks very much.  I appreciate the support.  I have every intention of open sourcing it.  I’ll add a license shortly.

**Comment by gitonthescene** [comment]
FWIW, I’ve added the MIT license
