### ISSUE TITLE
How can I use expandable content in org-mode?

### ISSUE THREAD

**Issue by avatar-lavventura** [wallyqs/org-ruby#97]
Related: https://emacs.stackexchange.com/a/75357/18414
> Unfortunately Org drawers are not rendered on Github though:

Markdown has expandable content option to hide and unhide a block of text or a video. This option most often used in README.md that is view through github.

Example [from](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab):

```markdown
<details>
  <summary>Click me</summary>
  
  ### Heading
  1. Foo
  2. Bar
     * Baz
     * Qux

  ### Some Code
  ```js
  function logSomething(something) {
    console.log('Something', something);
  }
</details>
```

![](https://i.stack.imgur.com/SxV5t.png)

When `>` is clicked it gets expended.

Is it possible to achieve same property on org-mode for the `README.org` files?

------

Response from GitHub Support:

> GitHub (GitHub Support)
> Jan 18, 2023, 10:48 PM UTC
> 
> Hi Alper,
> 
> Thanks for reaching out to GitHub Support about support for drawers in org-mode on GitHub.
> 
> I tested this and verified that org-mode drawers do not work on GitHub.com. Taking a look at this I see that our support for org-mode relies on the [wallyqs/org-ruby](https://github.com/wallyqs/org-ruby) open source project. I see that they note that they do not provide support for all org-mode features, so it appears that drawers is among the unsupported features. I would recommend filing an issue in that repository to ask that support for drawers be added.
> 
> https://github.com/wallyqs/org-ruby/issues
> 
> I hope that this is of help to you. Please let me know if I can be of further assistance.

**Comment by rgb-24bit** [comment]
https://gist.github.com/rgb-24bit/3bfff87768e954642191c9e6693dc11c
```org
#+HTML: <details><summary>Click me</summary>

- item1
- item2

#+HTML: </details>
```

**Comment by avatar-lavventura** [comment]
@rgb-24bit Thanks this is golden!
